language: java
sudo: required
dist: trusty
jdk:
  - oraclejdk8
script:
  - src/main/resources/bin/ubuntu/lli -version
  - ./gradlew check -i
notifications:
  email:
    on_success: never
    on_failure: change