#! /usr/bin/env python
nodes = "program, mainClassDecl, classDecl, classVarDecl, methodDecl, formal, type, stmt, varDecl, block, ifElse, whileDecl, print, assigment, expr, logicalOr, logicalAnd, equalsOrNotEquals, relation, plusOrMinus, multOrDiv, unary, atom"

nodes = nodes.split(", ")


for node in nodes:
  node = node.title() + "Node"
  with open('src/main/java/edu/rosehulman/csse/mjc/ast/' + node + '.java', 'w') as f:
    f.write("""
package edu.rosehulman.csse.mjc.ast;

public class """ + node +  """ extends ASTNode {
}
  """)
